### ISSUE TITLE
Improve extensibility of SHAD system

### ISSUE THREAD

**Issue by tjstavenger-pnnl** [pnnl/SHAD#11]
Currently new systems that implement the SHAD API must all be contained within the same SHAD source code repository due to the way imports/includes are handled. Refactor the includes & build to support extending SHAD from separate Git repositories.

**Comment by tjstavenger-pnnl** [comment]
code development ongoing in improve-extensibility branch: https://github.com/pnnl/SHAD/tree/improve-extensibility

**Comment by mminutoli** [comment]
Please start all your commit messages with

[pnnl/SHAD#<issue_number>]

GitHub will "connect" your work with the issue in the bug tracker.

**Comment by mminutoli** [comment]
If you want (and you know how to do it), you can rewrite the history of your branch with git rebase.
