### ISSUE TITLE
Add build support for reporting unit & performance test trends

### ISSUE THREAD

**Issue by tjstavenger-pnnl** [pnnl/SHAD#15]
This ticket is to track work on changing the build to report test case pass/fail trends as well as performance trends.

**Comment by mminutoli** [comment]
What do you mean? My friend Travis remembers everything https://travis-ci.org/pnnl/SHAD/builds

**Comment by tjstavenger-pnnl** [comment]
Yes, kind of ... but not like this https://wiki.jenkins.io/display/JENKINS/JUnit+graph

Or once we get the performance tests active like http://jenkinsci.github.io/performance-plugin/Reporting.html

Obviously these are Jenkins examples, but they bring out more clearly your trends. I'm looking into reporting like this from Travis CI, but I believe it may be limited to just a console log vs any true reporting. The hope & intent is to be able to report via builds to sponsors & users the performance results of tests over time as SHAD is developed.

**Comment by mminutoli** [comment]
Considering that we have a test randomly failing for some nasty bug somewhere [pnnl/SHAD#5]. I would consider this premature and low priority for the moment.

@VitoCastellana What do you think?
